export const mathematicsQuickSearchKeyWords: string[] = [
    "3-D Object",
    "3-D Shape",
    "3-D Space",
    "2-D Object",
    "2-D Shape",
    "Subtract zero",
    "Add zero",
    "Addition",
    "Subtraction",
    "Multiplication",
    "Division",
    "Fractions",
    "Decimal",
    "Percentage",
    "Exponent",
    "Equation",
    "Equality",
    "Equalities",
    "Inequality",
    "Inequalities",
    "First-hand",
    "Second-hand",
    "Independent",
    "Fact families",
    "Permutations",
    "Combinations",
    "Identify",
    "Compatible numbers",
    "Angle",
    "Degree",
    "Slope",
    "Linear",
    "Unit circle",
    "Sine law",
    "Cosine law",
    "Arrays",
    "Equal groups",
    "Repeated addition",
    "Repeated subtraction",
    "Base-10",
    "Place value",
    "Expanded notation",
    "Ten frames",
    "Number line",
    "Skip counting",
    "Counting",
    "Even",
    "Odd",
    "Ordinal numbers",
    "Pattern",
    "Pattern rule",
    "Sequence",
    "Grouping",
    "Compare",
    "Perimeter",
    "Area",
    "Surface Area",
    "Volume",
    "Measure",
    "Length",
    "Mass",
    "Capacity",
    "Unit measure",
    "Estimation",
    "Referents",
    "Mental Mathematics",
    "Problem-solving",
    "Graph",
    "Chart",
    "Line plot",
    "Bar graph",
    "Pictograph",
    "Concrete graph",
    "Statistics",
    "Data collection",
    "Collecting data",
    "Tally marks",
    "Population",
    "Probablity",
    "Quadrilaterals",
    "Polygon",
    "Shapes",
    "Orientation",
    "Cartesian plane",
    "Clock",
    "Symbols",
    "Balance scale",
    "Drawing",
    "Visualization",
    "coins"
]

export const scienceQuickSearchKeywords: string[] = [
    // Scientific Skills & Inquiry
    "Scientific method",
    "Observation",
    "Hypothesis",
    "Prediction",
    "Investigation",
    "Experiment",
    "Inquiry process",
    "Variables",
    "Evidence",
    "Measurement",
    "Safety",
    "Tools",
    "Technology",
    "Data table",
    "Graph",
    "Interpret results",
    "Communicate findings",

    // Life Science (K–8)
    "Living things",
    "Plants",
    "Animals",
    "Habitats",
    "Communities",
    "Ecosystems",
    "Food chain",
    "Adaptation",
    "Biodiversity",
    "Life cycle",
    "Reproduction",
    "Growth and change",

    // Physical Science
    "Matter",
    "Solids",
    "Liquids",
    "Gases",
    "Properties",
    "Mixtures",
    "Changes of state",
    "Forces",
    "Motion",
    "Simple machines",
    "Energy",
    "Sound",
    "Light",
    "Heat",
    "Electricity",
    "Magnetism",
    "Flight",
    "Pressure",
    "Buoyancy",

    // Earth & Space Science
    "Weather",
    "Climate",
    "Seasons",
    "Water cycle",
    "Air",
    "Soil",
    "Erosion",
    "Rock",
    "Mineral",
    "Volcano",
    "Earthquake",
    "Solar system",
    "Planet",
    "Moon",
    "Sun",
    "Star",
    "Constellation",
    "Gravity",

    // Environmental Awareness
    "Sustainability",
    "Natural resources",
    "Pollution",
    "Recycling",
    "Conservation",
    "Human impact",
    "Stewardship",
];


export const biologyQuickSearchKeywords: string[] = [
    // Scientific Inquiry
    "Scientific investigation",
    "Controlled experiment",
    "Data analysis",
    "Microscope",
    "Measurement",
    "Observation",

    // Diversity & Evolution
    "Classification",
    "Taxonomy",
    "Kingdom",
    "Species",
    "Biodiversity",
    "Evolution",
    "Natural selection",
    "Adaptation",
    "Variation",
    "Phylogeny",

    // Genetics
    "DNA",
    "RNA",
    "Chromosome",
    "Gene",
    "Allele",
    "Dominant",
    "Recessive",
    "Genotype",
    "Phenotype",
    "Heredity",
    "Punnett square",
    "Mutation",
    "Biotechnology",
    "Genetic engineering",

    // Cells & Systems
    "Cell",
    "Cell membrane",
    "Nucleus",
    "Mitochondria",
    "Chloroplast",
    "Organ system",
    "Respiratory system",
    "Circulatory system",
    "Digestive system",
    "Nervous system",
    "Excretory system",
    "Homeostasis",
    "Osmosis",
    "Diffusion",

    // Human Biology
    "Organ",
    "Tissue",
    "Enzyme",
    "Hormone",
    "Metabolism",
    "Reproduction",
    "Fertilization",
    "Embryo",
    "Immunity",
    "Health",
    "Disease",

    // Ecology
    "Ecosystem",
    "Population",
    "Community",
    "Habitat",
    "Energy flow",
    "Food web",
    "Trophic level",
    "Biogeochemical cycle",
    "Carbon cycle",
    "Nitrogen cycle",
    "Photosynthesis",
    "Cellular respiration",
    "Succession",
    "Biosphere",
    "Sustainability",

    // Biotechnology & Environment
    "Cloning",
    "Genetic modification",
    "Ethics",
    "Conservation",
    "Biodiversity loss",
    "Human impact",
];


export const socialStudiesQuickSearchKeyWords: string[] = [
    // Disciplines
    "Social Studies",
    "History",
    "Geography",
    "Civics",
    "Economics",
    "Government",
    "Citizenship",
    "Culture",
    "Community",
    "Identity",
    "Heritage",

    // Manitoba & Canada
    "Manitoba",
    "Winnipeg",
    "Prairies",
    "Canada",
    "Confederation",
    "New France",
    "Fur Trade",
    "Hudson Bay",
    "Metis",
    "Indigenous Peoples",
    "First Nations",
    "Inuit",
    "Treaty",
    "Residential Schools",
    "Immigration",
    "Francophone",
    "Anglophone",
    "Bilingualism",
    "Canadian Charter",
    "Democracy",
    "Citizenship Rights",

    // Geography
    "Map",
    "Globe",
    "Compass",
    "Latitude",
    "Longitude",
    "Region",
    "Continent",
    "Ocean",
    "Landform",
    "Climate",
    "Natural resources",
    "Environment",
    "Human-environment interaction",
    "Global interdependence",

    // Historical Thinking
    "Timeline",
    "Cause and consequence",
    "Change and continuity",
    "Primary source",
    "Artifact",
    "Interpretation",
    "Evidence",
    "Perspective",

    // Economics
    "Trade",
    "Resources",
    "Production",
    "Consumption",
    "Market",
    "Supply and demand",
    "Money",
    "Bank",
    "Tax",
    "Employment",

    // Citizenship & Values
    "Fairness",
    "Justice",
    "Respect",
    "Diversity",
    "Democracy",
    "Responsibility",
    "Decision making",
    "Leadership",
    "Participation",
    "Community service",
    "Human rights",
    "Global citizenship",

    // Global Connections
    "World community",
    "International relations",
    "United Nations",
    "Peacekeeping",
    "Sustainability",
];
