export const mathematicsQuickSearchKeyWords: string[] = [
    "3-D Object",
    "3-D Shape",
    "3-D Space",
    "2-D Object",
    "2-D Shape",
    "Subtract zero",
    "Add zero",
    "Addition",
    "Subtraction",
    "Multiplication",
    "Division",
    "Fractions",
    "Decimal",
    "Percentage",
    "Exponent",
    "Equation",
    "Equality",
    "Equalities",
    "Inequality",
    "Inequalities",
    "First-hand",
    "Second-hand",
    "Independent",
    "Fact families",
    "Permutations",
    "Combinations",
    "Identify",
    "Compatible numbers",
    "Angle",
    "Degree",
    "Slope",
    "Linear",
    "Unit circle",
    "Sine law",
    "Cosine law",
    "Arrays",
    "Equal groups",
    "Repeated addition",
    "Repeated subtraction",
    "Base-10",
    "Place value",
    "Expanded notation",
    "Ten frames",
    "Number line",
    "Skip counting",
    "Counting",
    "Even",
    "Odd",
    "Ordinal numbers",
    "Pattern",
    "Pattern rule",
    "Sequence",
    "Grouping",
    "Compare",
    "Perimeter",
    "Area",
    "Surface Area",
    "Volume",
    "Measure",
    "Length",
    "Mass",
    "Capacity",
    "Unit measure",
    "Estimation",
    "Referents",
    "Mental Mathematics",
    "Problem-solving",
    "Graph",
    "Chart",
    "Line plot",
    "Bar graph",
    "Pictograph",
    "Concrete graph",
    "Statistics",
    "Data collection",
    "Collecting data",
    "Tally marks",
    "Population",
    "Probablity",
    "Quadrilaterals",
    "Polygon",
    "Shapes",
    "Orientation",
    "Cartesian plane",
    "Clock",
    "Symbols",
    "Balance scale",
    "Drawing",
    "Visualization",
    "coins"
]

export const scienceQuickSearchKeywords: string[] = [
]

export const biologyQuickSearchKeywords: string[] = [

]

export const socialStudiesQuickSearchKeyWords: string[] = [
    "Social Studies",
    "History",
    "Geography",
    "Science",
    "Mathematics",
    "English",
    "Reading",
    "Writing",
    "Speaking",
]